### ISSUE TITLE
bruh am new help

### ISSUE THREAD

**Issue by Vkie0** [httpsprotocol/Valorant-External#1]
where can i download the launcher xD

**Comment by httpsprotocol** [comment]
> where can i download the launcher xD

Hello, Sorry there were some issues with the launcher but I am pushing out an update right now. You can find the Launcher in the Releases Tab, should be named something like "Valorant Patch 6.08 / 6.07 C++" Either way if you find the Releases Tab there will only be one launcher, and thats the up-to-date one. :)
