### ISSUE TITLE
Virustotal says it has 32 suspicious trojans lol

### ISSUE THREAD

**Issue by BaritonePathfinding** [httpsprotocol/Valorant-External#10]
Trying to download this and uhm
 
![image](https://github.com/httpsprotocol/Valorant-External/assets/149338443/bb407d83-7746-4d94-bd6d-4cae15031ab4)

yeah....

**Comment by httpsprotocol** [comment]
Most of these AV's aren't reputable, and a game cheat is obviously going to get flagged. I forgot to push out that this respiratory is down as of now and isn't working, so that also adds on.
