### ISSUE TITLE
still undetected?

### ISSUE THREAD

**Issue by Okie12345** [httpsprotocol/Valorant-External#4]
if it is detected, what to use not to be detected too much

**Comment by httpsprotocol** [comment]
Still undetected, I'm always active on this repo and if its detected or there is an issue I remove the release.

**Comment by Okie12345** [comment]
so just let me get it straight, you say, that your public compiled cheat for game with very invasive ac and actual workers that check cheats and repair perfect ac for these cheats not to work (sorry for bad english)

**Comment by Okie12345** [comment]
you might as well be RIOT employee xD
